### ISSUE TITLE
Self is immutable inside class extension

### ISSUE THREAD

**Issue by robin-nyman-mi** [onevcat/Kingfisher#1064]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [X] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.
- [X] I have searched in [existing issues](https://github.com/onevcat/Kingfisher/issues?utf8=✓&q=is%3Aissue), but did not find a same one.
- [X] I want to report a problem instead of asking a question. It'd better to use [kingfisher tag in Stack Overflow](http://stackoverflow.com/questions/tagged/kingfisher) to ask a question.

#### What

After upgrading from 4.x to 5.x, it's no longer possible to set the 'indicatorType' inside of a class extension.

> Cannot assign to property: 'self' is immutable

#### Reproduce

Create a UIImageView extension and try to set the indicatorType inside a function.

```
extension UIImageView {
  func doSomething() {
    self.kf.indicatorType = .activity // Error
  }
}
```

#### Other Comment

It's still possible to call functions such as 'setImage'.

**Comment by onevcat** [comment]
Yes, now the `kf` returns a struct instead of class. This change is for performance, and for your case, try:

```swift
extension UIImageView {
    func doSomething() {
        var kf = self.kf
        kf.indicatorType = .activity
    }
}
```

**Comment by robin-nyman-mi** [comment]
Yes, this fixes the compilation error.
I was worried that the changes would not be reflected, but it seems to work.

Thanks for the help.
