### ISSUE TITLE
Kingfisher 8.6 binary missing symbols on Xcode 16.2

### ISSUE THREAD

**Issue by battlmonstr** [onevcat/Kingfisher#2446]
Kingfisher 8.5 binary works on Xcode 16.2, but Kingfisher 8.6 binary produces compilation errors about a missing setImage method:

```
import UIKit
import Kingfisher

class ViewController: UIViewController {
  override func viewDidLoad() {
    super.viewDidLoad()
    let i = UIImageView()
    i.kf.cancelDownloadTask()
    i.kf.setImage(with: URL(string: "")!) // fails to compile
  }
}
```

error:
```
ViewController.swift:9:10: error: value of type 'KingfisherWrapper<UIImageView>' has no member 'setImage'
```

Is Xcode 16.2 support dropped in 8.6?

**Comment by battlmonstr** [comment]
@onevcat thanks for an update

I've retried and it does work on Xcode 16.4, but fails on 16.2 and 16.1.
We need to update our CI to 16.4.
I'll close the issue.

P.S. yes, I was using the binary from https://github.com/onevcat/Kingfisher/releases/download/8.6.0/Kingfisher-iOS-8.6.0.xcframework.zip
